ALTER TABLE orders ALTER COLUMN total TYPE NUMERIC(12,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_fee NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payable_total NUMERIC(12,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status TEXT NOT NULL DEFAULT 'unverified';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS request_key TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS request_fingerprint TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS courier_id INTEGER;
UPDATE orders SET payable_total = total + CASE WHEN total >= 5000 THEN 0 ELSE 290 END,
 delivery_fee = CASE WHEN total >= 5000 THEN 0 ELSE 290 END WHERE payable_total IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS orders_request_key ON orders(telegram_user_id, request_key);
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS synonyms TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS seasonal BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS popular BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS package_label TEXT NOT NULL DEFAULT '';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS image TEXT NOT NULL DEFAULT '';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS icon TEXT NOT NULL DEFAULT '📦';
CREATE TABLE IF NOT EXISTS payments (
 id UUID PRIMARY KEY, telegram_id BIGINT NOT NULL, kind TEXT NOT NULL,
 order_id INTEGER REFERENCES orders(id), request_key TEXT NOT NULL,
 amount_minor INTEGER NOT NULL CHECK(amount_minor > 0), subscription_days INTEGER,
 provider_id TEXT UNIQUE, confirmation_url TEXT, status TEXT NOT NULL DEFAULT 'pending',
 applied_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(telegram_id, request_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS payments_one_order ON payments(order_id) WHERE order_id IS NOT NULL AND status != 'canceled';
CREATE TABLE IF NOT EXISTS product_reviews (
 id SERIAL PRIMARY KEY, product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
 telegram_id BIGINT NOT NULL, rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),
 message TEXT NOT NULL DEFAULT '', visible BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(product_id, telegram_id)
);
CREATE TABLE IF NOT EXISTS warehouses (
 id SERIAL PRIMARY KEY, name TEXT NOT NULL, address TEXT NOT NULL,
 latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL,
 radius_km DOUBLE PRECISION NOT NULL DEFAULT 30, preparation_minutes INTEGER NOT NULL DEFAULT 30,
 open_hour INTEGER NOT NULL DEFAULT 9, close_hour INTEGER NOT NULL DEFAULT 22,
 active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS couriers (
 id SERIAL PRIMARY KEY, name TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '',
 warehouse_id INTEGER REFERENCES warehouses(id), active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS delivery_settings (
 id INTEGER PRIMARY KEY CHECK(id=1), base_fee INTEGER NOT NULL DEFAULT 290,
 per_km INTEGER NOT NULL DEFAULT 0, free_from INTEGER NOT NULL DEFAULT 5000,
 speed_kmh INTEGER NOT NULL DEFAULT 20, road_factor NUMERIC NOT NULL DEFAULT 1.4
);
INSERT INTO delivery_settings(id) VALUES(1) ON CONFLICT DO NOTHING;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS provider_name TEXT NOT NULL DEFAULT 'yookassa';
CREATE TABLE IF NOT EXISTS payment_settings (
 id INTEGER PRIMARY KEY CHECK(id=1), active_provider TEXT NOT NULL DEFAULT 'yookassa',
 public_url TEXT NOT NULL DEFAULT '', allow_test BOOLEAN NOT NULL DEFAULT FALSE
);
INSERT INTO payment_settings(id) VALUES(1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS payment_credentials (
 provider TEXT PRIMARY KEY, encrypted TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE users ALTER COLUMN total_spent TYPE NUMERIC(12,2);
