const img = (seed: string, text: string) =>
  `https://dummyimage.com/600x630/2e7d32/ffffff.png&text=${encodeURIComponent(text)}${encodeURIComponent(' #' + seed)}`;

export const seedProducts = [
  {
    name: 'Яблоки Гала',
    description: 'Сочные сладкие яблоки местного урожая. Отлично подходят для перекуса и выпечки.',
    price: 189,
    image: img('p1', 'Яблоки Гала'),
    category: 'fruits-vegetables',
    unit: 'кг',
    weight: null,
    rating: 4.8,
    reviewsCount: 342,
    inStock: true,
    badge: 'Свежее',
  },
  {
    name: 'Бананы',
    description: 'Спелые бананы премиум-класса. Богаты калием и витаминами.',
    price: 129,
    oldPrice: 149,
    image: img('p2', 'Бананы'),
    category: 'fruits-vegetables',
    unit: 'кг',
    weight: null,
    rating: 4.6,
    reviewsCount: 518,
    inStock: true,
    badge: '-13%',
  },
  {
    name: 'Молоко 3,2%',
    description: 'Натуральное цельное молоко пастеризованное. Без сухого молока и консервантов.',
    price: 96,
    image: img('p3', 'Молоко 3,2%'),
    category: 'dairy',
    unit: 'шт',
    weight: 0.93,
    rating: 4.7,
    reviewsCount: 890,
    inStock: true,
  },
  {
    name: 'Сыр «Российский»',
    description: 'Классический полутвёрдый сыр с лёгкой кислинкой. Выдержка 60 дней.',
    price: 269,
    oldPrice: 329,
    image: img('p4', 'Сыр Российский'),
    category: 'dairy',
    unit: 'шт',
    weight: 0.3,
    rating: 4.5,
    reviewsCount: 267,
    inStock: true,
    badge: 'Хит',
  },
  {
    name: 'Куриное филе охлаждённое',
    description: 'Филе грудки охлаждённое, без кожи и костей. Хранение при 0…+4 °C.',
    price: 349,
    oldPrice: 429,
    image: img('p5', 'Филе курицы'),
    category: 'meat',
    unit: 'кг',
    weight: null,
    rating: 4.4,
    reviewsCount: 402,
    inStock: true,
    badge: '-19%',
  },
  {
    name: 'Стейк лосося с/м',
    description: 'Стейк лосося с/м, порционно. Идеален для запекания и гриля.',
    price: 1290,
    image: img('p6', 'Лосось'),
    category: 'fish',
    unit: 'кг',
    weight: null,
    rating: 4.9,
    reviewsCount: 176,
    inStock: true,
  },
  {
    name: 'Хлеб «Бородинский»',
    description: 'Тёмный ржано-пшеничный хлеб с кориандром. Выпечен сегодня.',
    price: 62,
    image: img('p7', 'Бородинский'),
    category: 'bakery',
    unit: 'шт',
    weight: 0.4,
    rating: 4.8,
    reviewsCount: 1230,
    inStock: true,
    badge: 'Свежее',
  },
  {
    name: 'Рис круглозёрный',
    description: 'Круглозёрный рис для супов, каш и японской кухни. Первый сорт.',
    price: 149,
    oldPrice: 189,
    image: img('p8', 'Рис'),
    category: 'pantry',
    unit: 'шт',
    weight: 0.9,
    rating: 4.5,
    reviewsCount: 358,
    inStock: true,
    badge: '-21%',
  },
  {
    name: 'Макароны спагетти',
    description: 'Спагетти из твёрдых сортов пшеницы. Варка 8 минут.',
    price: 119,
    image: img('p9', 'Спагетти'),
    category: 'pantry',
    unit: 'шт',
    weight: 0.45,
    rating: 4.6,
    reviewsCount: 421,
    inStock: true,
  },
  {
    name: 'Кофе молотый',
    description: 'Молотый кофе средней обжарки. Вакуумная упаковка 190 г.',
    price: 449,
    oldPrice: 529,
    image: img('p10', 'Кофе'),
    category: 'pantry',
    unit: 'шт',
    weight: 0.19,
    rating: 4.7,
    reviewsCount: 985,
    inStock: true,
    badge: '-15%',
  },
  {
    name: 'Вода питьевая 1,5 л',
    description: 'Питьевая вода первой категории негазированная. Удобная бутылка.',
    price: 45,
    image: img('p11', 'Вода 1,5 л'),
    category: 'drinks',
    unit: 'шт',
    weight: 1.5,
    rating: 4.3,
    reviewsCount: 2104,
    inStock: true,
  },
  {
    name: 'Мороженое пломбир',
    description: 'Классический пломбир на сливках. В вафельном стаканчике.',
    price: 89,
    image: img('p12', 'Пломбир'),
    category: 'frozen',
    unit: 'шт',
    weight: 0.1,
    rating: 4.8,
    reviewsCount: 676,
    inStock: true,
    badge: 'Топ',
  },
];
